services:
  - type: web
    name: basti-ki-pathshala
    env: node
    buildCommand: |
      npm install
      cd client && npm install
      cd client && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000 